//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eclipse1807.BlishHUD.FishingBuddy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eclipse1807.BlishHUD.FishingBuddy.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        internal static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adds new line.
        /// </summary>
        internal static string AddsNewLines {
            get {
                return ResourceManager.GetString("AddsNewLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascended.
        /// </summary>
        internal static string Ascended {
            get {
                return ResourceManager.GetString("Ascended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boreal Fish.
        /// </summary>
        internal static string Boreal_Fish {
            get {
                return ResourceManager.GetString("Boreal Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-left.
        /// </summary>
        internal static string Bottom_left {
            get {
                return ResourceManager.GetString("Bottom-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-right.
        /// </summary>
        internal static string Bottom_right {
            get {
                return ResourceManager.GetString("Bottom-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavern Fish.
        /// </summary>
        internal static string Cavern_Fish {
            get {
                return ResourceManager.GetString("Cavern Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Fish.
        /// </summary>
        internal static string Channel_Fish {
            get {
                return ResourceManager.GetString("Channel Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal Fish.
        /// </summary>
        internal static string Coastal_Fish {
            get {
                return ResourceManager.GetString("Coastal Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact: #1 [#6]\\nBait: #2\\nHole: #4 (#3)\\n@7\n.
        /// </summary>
        internal static string CompactTooltip {
            get {
                return ResourceManager.GetString("CompactTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn.
        /// </summary>
        internal static string Dawn {
            get {
                return ResourceManager.GetString("Dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn/Dusk.
        /// </summary>
        internal static string Dawn_Dusk {
            get {
                return ResourceManager.GetString("Dawn/Dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Fishing Hole.
        /// </summary>
        internal static string Deep_Fishing_Hole {
            get {
                return ResourceManager.GetString("Deep Fishing Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert Fish.
        /// </summary>
        internal static string Desert_Fish {
            get {
                return ResourceManager.GetString("Desert Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk.
        /// </summary>
        internal static string Dusk {
            get {
                return ResourceManager.GetString("Dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk/Dawn.
        /// </summary>
        internal static string Dusk_Dawn {
            get {
                return ResourceManager.GetString("Dusk/Dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        internal static string Exotic {
            get {
                return ResourceManager.GetString("Exotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        internal static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Eggs.
        /// </summary>
        internal static string Fish_Eggs {
            get {
                return ResourceManager.GetString("Fish Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favored Bait.
        /// </summary>
        internal static string FishFavoredBait {
            get {
                return ResourceManager.GetString("FishFavoredBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Hole.
        /// </summary>
        internal static string FishFishingHole {
            get {
                return ResourceManager.GetString("FishFishingHole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FishName {
            get {
                return ResourceManager.GetString("FishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Fish.
        /// </summary>
        internal static string FishPanelDrag {
            get {
                return ResourceManager.GetString("FishPanelDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Panel Location.
        /// </summary>
        internal static string FishPanelLocation {
            get {
                return ResourceManager.GetString("FishPanelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Size.
        /// </summary>
        internal static string FishPanelSize {
            get {
                return ResourceManager.GetString("FishPanelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @number uses default string, #number allows for more customization\n.
        /// </summary>
        internal static string FishPanelTooltipDescription {
            get {
                return ResourceManager.GetString("FishPanelTooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Day.
        /// </summary>
        internal static string FishTimeOfDay {
            get {
                return ResourceManager.GetString("FishTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishy Notes.
        /// </summary>
        internal static string FishyNotes {
            get {
                return ResourceManager.GetString("FishyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshwater Fish.
        /// </summary>
        internal static string Freshwater_Fish {
            get {
                return ResourceManager.GetString("Freshwater Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow Worms.
        /// </summary>
        internal static string Glow_Worms {
            get {
                return ResourceManager.GetString("Glow Worms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grotto Fish.
        /// </summary>
        internal static string Grotto_Fish {
            get {
                return ResourceManager.GetString("Grotto Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiju Minnows.
        /// </summary>
        internal static string Haiju_Minnows {
            get {
                return ResourceManager.GetString("Haiju Minnows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Caught.
        /// </summary>
        internal static string HiddenCaught {
            get {
                return ResourceManager.GetString("HiddenCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide In Combat.
        /// </summary>
        internal static string HideInCombat {
            get {
                return ResourceManager.GetString("HideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all fishing info in combat.
        /// </summary>
        internal static string HideInCombatDescription {
            get {
                return ResourceManager.GetString("HideInCombatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        internal static string Junk {
            get {
                return ResourceManager.GetString("Junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Align.
        /// </summary>
        internal static string LabelAlign {
            get {
                return ResourceManager.GetString("LabelAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Fish.
        /// </summary>
        internal static string Lake_Fish {
            get {
                return ResourceManager.GetString("Lake Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lava Beetles.
        /// </summary>
        internal static string Lava_Beetles {
            get {
                return ResourceManager.GetString("Lava Beetles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeches.
        /// </summary>
        internal static string Leeches {
            get {
                return ResourceManager.GetString("Leeches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        internal static string Legendary {
            get {
                return ResourceManager.GetString("Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Bugs.
        /// </summary>
        internal static string Lightning_Bugs {
            get {
                return ResourceManager.GetString("Lightning Bugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lutgardis Trout.
        /// </summary>
        internal static string Lutgardis_Trout {
            get {
                return ResourceManager.GetString("Lutgardis Trout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mackerel.
        /// </summary>
        internal static string Mackerel {
            get {
                return ResourceManager.GetString("Mackerel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterwork.
        /// </summary>
        internal static string Masterwork {
            get {
                return ResourceManager.GetString("Masterwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minnows.
        /// </summary>
        internal static string Minnows {
            get {
                return ResourceManager.GetString("Minnows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysterious Waters Fish.
        /// </summary>
        internal static string Mysterious_Waters_Fish {
            get {
                return ResourceManager.GetString("Mysterious Waters Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightcrawlers.
        /// </summary>
        internal static string Nightcrawlers {
            get {
                return ResourceManager.GetString("Nightcrawlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noxious Water Fish.
        /// </summary>
        internal static string Noxious_Water_Fish {
            get {
                return ResourceManager.GetString("Noxious Water Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offshore Fish.
        /// </summary>
        internal static string Offshore_Fish {
            get {
                return ResourceManager.GetString("Offshore Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Water.
        /// </summary>
        internal static string OpenWater {
            get {
                return ResourceManager.GetString("OpenWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish panel orientation.
        /// </summary>
        internal static string OrientationDescription {
            get {
                return ResourceManager.GetString("OrientationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polluted Lake Fish.
        /// </summary>
        internal static string Polluted_Lake_Fish {
            get {
                return ResourceManager.GetString("Polluted Lake Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarry Fish.
        /// </summary>
        internal static string Quarry_Fish {
            get {
                return ResourceManager.GetString("Quarry Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramshorn Snails.
        /// </summary>
        internal static string Ramshorn_Snails {
            get {
                return ResourceManager.GetString("Ramshorn Snails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare Fish.
        /// </summary>
        internal static string Rare_Fish {
            get {
                return ResourceManager.GetString("Rare Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display fish rarity border.
        /// </summary>
        internal static string RarityDescription {
            get {
                return ResourceManager.GetString("RarityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Hiding.
        /// </summary>
        internal static string ReasonForHiding {
            get {
                return ResourceManager.GetString("ReasonForHiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release for 1500 karma.
        /// </summary>
        internal static string Release_for_1500_karma {
            get {
                return ResourceManager.GetString("Release for 1500 karma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release for 2500 karma.
        /// </summary>
        internal static string Release_for_2500_karma {
            get {
                return ResourceManager.GetString("Release for 2500 karma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release for 350 karma.
        /// </summary>
        internal static string Release_for_350_karma {
            get {
                return ResourceManager.GetString("Release for 350 karma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Fish.
        /// </summary>
        internal static string River_Fish {
            get {
                return ResourceManager.GetString("River Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltwater Fish.
        /// </summary>
        internal static string Saltwater_Fish {
            get {
                return ResourceManager.GetString("Saltwater Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sardines.
        /// </summary>
        internal static string Sardines {
            get {
                return ResourceManager.GetString("Sardines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpions.
        /// </summary>
        internal static string Scorpions {
            get {
                return ResourceManager.GetString("Scorpions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish panel direction.
        /// </summary>
        internal static string SettingsDirectionDescription {
            get {
                return ResourceManager.GetString("SettingsDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Saltwater.
        /// </summary>
        internal static string SettingsDisplaySaltwater {
            get {
                return ResourceManager.GetString("SettingsDisplaySaltwater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Saltwater Fisher fish.
        /// </summary>
        internal static string SettingsDisplaySaltwaterDescription {
            get {
                return ResourceManager.GetString("SettingsDisplaySaltwaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Uncatchable.
        /// </summary>
        internal static string SettingsDisplayUncatchable {
            get {
                return ResourceManager.GetString("SettingsDisplayUncatchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display fish that cannot be caught at this time of day.
        /// </summary>
        internal static string SettingsDisplayUncatchableDescription {
            get {
                return ResourceManager.GetString("SettingsDisplayUncatchableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display World Class.
        /// </summary>
        internal static string SettingsDisplayWorldClass {
            get {
                return ResourceManager.GetString("SettingsDisplayWorldClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include World Class Fisher fish.
        /// </summary>
        internal static string SettingsDisplayWorldClassDescription {
            get {
                return ResourceManager.GetString("SettingsDisplayWorldClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Caught.
        /// </summary>
        internal static string SettingsIgnoreCaught {
            get {
                return ResourceManager.GetString("SettingsIgnoreCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore fish already counted towards achievements.
        /// </summary>
        internal static string SettingsIgnoreCaughtDescription {
            get {
                return ResourceManager.GetString("SettingsIgnoreCaughtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rarity.
        /// </summary>
        internal static string SettingsRarity {
            get {
                return ResourceManager.GetString("SettingsRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shore Fish.
        /// </summary>
        internal static string Shore_Fish {
            get {
                return ResourceManager.GetString("Shore Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrimplings.
        /// </summary>
        internal static string Shrimplings {
            get {
                return ResourceManager.GetString("Shrimplings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple: #1\\nBait: #2\\nHole: #4\\n@7\n.
        /// </summary>
        internal static string SimpleTooltip {
            get {
                return ResourceManager.GetString("SimpleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkfly Larvae.
        /// </summary>
        internal static string Sparkfly_Larvae {
            get {
                return ResourceManager.GetString("Sparkfly Larvae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Fishing Hole.
        /// </summary>
        internal static string Special_Fishing_Hole {
            get {
                return ResourceManager.GetString("Special Fishing Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Crushing Weight.
        /// </summary>
        internal static string Specialization_Collection__Crushing_Weight {
            get {
                return ResourceManager.GetString("Specialization Collection: Crushing Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Dichotomy.
        /// </summary>
        internal static string Specialization_Collection__Dichotomy {
            get {
                return ResourceManager.GetString("Specialization Collection: Dichotomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Gravity.
        /// </summary>
        internal static string Specialization_Collection__Gravity {
            get {
                return ResourceManager.GetString("Specialization Collection: Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Percussive Maintenance.
        /// </summary>
        internal static string Specialization_Collection__Percussive_Maintenance {
            get {
                return ResourceManager.GetString("Specialization Collection: Percussive Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Possession.
        /// </summary>
        internal static string Specialization_Collection__Possession {
            get {
                return ResourceManager.GetString("Specialization Collection: Possession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Prima Donna.
        /// </summary>
        internal static string Specialization_Collection__Prima_Donna {
            get {
                return ResourceManager.GetString("Specialization Collection: Prima Donna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Purifier.
        /// </summary>
        internal static string Specialization_Collection__Purifier {
            get {
                return ResourceManager.GetString("Specialization Collection: Purifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: Quietus.
        /// </summary>
        internal static string Specialization_Collection__Quietus {
            get {
                return ResourceManager.GetString("Specialization Collection: Quietus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization Collection: The Keenest Cut.
        /// </summary>
        internal static string Specialization_Collection__The_Keenest_Cut {
            get {
                return ResourceManager.GetString("Specialization Collection: The Keenest Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Day.
        /// </summary>
        internal static string TimeOfDay {
            get {
                return ResourceManager.GetString("TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Time Display.
        /// </summary>
        internal static string TimeOfDayHide {
            get {
                return ResourceManager.GetString("TimeOfDayHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option to hide time display.
        /// </summary>
        internal static string TimeOfDayHideDescription {
            get {
                return ResourceManager.GetString("TimeOfDayHideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Time Label.
        /// </summary>
        internal static string TimeOfDayHideLabel {
            get {
                return ResourceManager.GetString("TimeOfDayHideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide clock time label display.
        /// </summary>
        internal static string TimeOfDayHideLabelDescription {
            get {
                return ResourceManager.GetString("TimeOfDayHideLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Label Position.
        /// </summary>
        internal static string TimeOfDayLabelPosition {
            get {
                return ResourceManager.GetString("TimeOfDayLabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock display label alignment.
        /// </summary>
        internal static string TimeOfDayLabelPositionDescription {
            get {
                return ResourceManager.GetString("TimeOfDayLabelPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Time Display.
        /// </summary>
        internal static string TimeOfDayPanelDrag {
            get {
                return ResourceManager.GetString("TimeOfDayPanelDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag time of day display.
        /// </summary>
        internal static string TimeOfDayPanelDragDescription {
            get {
                return ResourceManager.GetString("TimeOfDayPanelDragDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Day Details Location.
        /// </summary>
        internal static string TimeOfDayPanelLoc {
            get {
                return ResourceManager.GetString("TimeOfDayPanelLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Day Size.
        /// </summary>
        internal static string TimeOfDaySize {
            get {
                return ResourceManager.GetString("TimeOfDaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Display.
        /// </summary>
        internal static string TooltipDisplay {
            get {
                return ResourceManager.GetString("TooltipDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-left.
        /// </summary>
        internal static string Top_left {
            get {
                return ResourceManager.GetString("Top-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-right.
        /// </summary>
        internal static string Top_right {
            get {
                return ResourceManager.GetString("Top-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used as bait.
        /// </summary>
        internal static string Used_as_bait {
            get {
                return ResourceManager.GetString("Used as bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for Daijun Bay renown heart.
        /// </summary>
        internal static string Used_for_Daijun_Bay_renown_heart {
            get {
                return ResourceManager.GetString("Used for Daijun Bay renown heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for Shinota Shore renown heart.
        /// </summary>
        internal static string Used_for_Shinota_Shore_renown_heart {
            get {
                return ResourceManager.GetString("Used for Shinota Shore renown heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic Fish.
        /// </summary>
        internal static string Volcanic_Fish {
            get {
                return ResourceManager.GetString("Volcanic Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wreckage Site.
        /// </summary>
        internal static string Wreckage_Site {
            get {
                return ResourceManager.GetString("Wreckage Site", resourceCulture);
            }
        }
    }
}
